In [1]:
import numpy as np

# Part 1

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
type()

numpy.ndarray

In [8]:
# 2-D matrix
mylist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
mymatrix = np.array(mylist)

In [11]:
mymatrix.shape

(3, 3)

In [12]:
# arange([start,] stop[, step,], dtype=None, *, like=None)

np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
# 0. is float number

In [15]:
# 4 by 10 matrix with zero
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
# 5 by 5 matrix with 1
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [18]:
# Python list is not multiply scalar
[1, 1, 1, 1] * 5

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [19]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
# np.eye 
# Return a 2-D array with ones on the diagonal and zeros elsewhere.

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Part 2

In [21]:
# Random number between 0 and 1 only 1 number
np.random.rand(1)

array([0.17695977])

In [22]:
np.random.rand(5)

array([0.5443298 , 0.23958482, 0.74453146, 0.31144155, 0.98364735])

In [23]:
# Random normal distribution
np.random.randn(5,5)

array([[ 1.20310053,  2.77962406, -0.92015598,  1.23813003,  2.26905325],
       [ 0.75935053, -0.65518801, -0.1867351 , -0.32012353, -1.26206949],
       [-1.33389926,  1.61705231, -0.4044399 ,  0.25516631, -2.4537326 ],
       [ 1.28589604,  0.73222673, -0.63599382, -0.81051624,  1.63957251],
       [ 0.16774429, -1.45487135,  0.60564876, -0.34263477, -0.02997204]])

In [24]:
# Random number between 1-100
np.random.randint(1, 100)

18

In [25]:
# Random number between 1-100 and return 10 numbers
np.random.randint(1, 100, 10)

array([71, 60, 80, 81, 71,  1, 67, 52, 83,  6])

In [27]:
np.random.seed(888)
np.random.rand(4)

array([0.85956061, 0.1645695 , 0.48347596, 0.92102727])

In [28]:
np.random.rand(4)

array([0.42855644, 0.05746009, 0.92500743, 0.65760154])

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0, 50, 10)

In [32]:
ranarr

array([ 3, 16, 38, 26, 19, 26, 18, 46, 30,  1])

In [33]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.reshape(5, 3)

ValueError: cannot reshape array of size 25 into shape (5,3)

In [35]:
ranarr

array([ 3, 16, 38, 26, 19, 26, 18, 46, 30,  1])

In [36]:
ranarr.max()

46

In [37]:
ranarr.min()

1

In [39]:
# Get index of max value
ranarr.argmax()

7

In [41]:
# Get index of min value
ranarr.argmin()

9

In [42]:
ranarr.dtype

dtype('int64')