In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# arr[index]
arr[8]

8

In [5]:
# arr[start:end]
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

# NumPy Array Broadcasting

In [9]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [11]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# Slicing

In [12]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy()

In [18]:
arr_copy[:] = 1000

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing on 2D array

In [20]:
arr_2d = np.array([[5, 10, 15],[20, 25, 30],[35, 40, 45]])

In [21]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
arr_2d.shape

(3, 3)

In [23]:
# arr_2d[row]
arr_2d[1]

array([20, 25, 30])

In [24]:
# arr_2d[row][column]
arr_2d[1][1]

25

In [27]:
# arr_2d[row, column]
arr_2d[1,1]

25

In [25]:
arr_2d[2,2]

45

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
# arr_2d[row(start:end)]
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [31]:
# arr_2d[row(start:end), column(start:end)]
arr_2d[:2, :2]

array([[ 5, 10],
       [20, 25]])

# Conditonal selection

In [32]:
arr = np.arange(1, 11)

In [33]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [34]:
bool_arr = arr > 4

In [35]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [37]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr[arr == 2]

array([2])

In [39]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])