**1. Import NumPy as np**

In [1]:
import numpy as np

**2. Create an array of 10 zeros**

In [2]:
arr_zeros = np.zeros(10)

In [4]:
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**3. Create an array of 10 ones**

In [5]:
arr_ones = np.ones(10)

In [6]:
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**4. Create an array of 10 fives**

In [9]:
arr_five = np.ones(10) * 5

In [10]:
arr_five

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**5. Create an array of integers from 10 to 50**

In [82]:
arr = np.arange(10, 51)

In [83]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**6. Create an array of all the even intergers from 10 to 50**

In [84]:
arr = np.arange(10, 51, 2)

In [85]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [19]:
arr_2d = np.arange(0,9).reshape(3,3)

In [20]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**8. Create a 3x3 identity matrix**

In [22]:
arr = np.eye((3))

In [23]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**9. Use NumPy to generate a random number between 0 and 1**

In [27]:
np.random.random(1)

array([0.56151789])

**10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution**

In [28]:
np.random.randn(25)

array([ 0.79045021,  0.5721088 , -0.20084829, -0.06297273, -0.97829888,
        1.23468845, -0.38966947,  0.22601291,  1.85927426, -1.00346701,
       -1.31615738, -1.58576208, -0.25757888,  1.11317571, -0.14217561,
       -0.86932437, -1.1711286 , -0.61027821, -0.1161936 ,  2.14764203,
       -1.22254024,  1.09216891,  0.58405104,  0.4521338 , -0.4391984 ])

**11. Create the matrix 10x10 with step size 0.01**

In [87]:
arr = np.arange(0.01, 1.01, 0.01)

# arr = np.arange(1, 101)/100
# arr.reshape(10, 10)

In [58]:
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**12. Create an array of 20 linearly spaced point between 0 and 1**

In [60]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# NumPy Indexing and Selection

In [61]:
mat = np.arange(1, 26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**13. Write code that reproduces the output start from where i=3, j=2**

In [64]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

**14. Write code that reproduces the output where i=4, j=5**

In [65]:
mat[3,4]

20

**15. Write code that reproduces the output column 2 from rows 1-3**

In [88]:
mat[:3, 1].reshape(3,1)

# mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

**16. Write code that reproduces the output show last row**

In [89]:
mat[4,:]

# mat[4]

array([21, 22, 23, 24, 25])

**17. Write code that reproduces the output only 2 last row**

In [90]:
mat[3:,:]

# mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# NumPy Operations

**18. Get the sum of all the values in mat**

In [78]:
mat.sum()

325

**19. Get the standard deviation of the values in mat**

In [79]:
mat.std()

7.211102550927978

**20. Get the sum of all the columns in mat**

In [81]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Bonus Question
We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers?

In [92]:
np.random.seed(888)
np.random.rand(1)

array([0.85956061])